[profile.default]
evm_version = "shanghai"
solc_version = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
#evm_version = "paris"
bytecode_hash = "none"

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[invariant]
runs = 128
depth = 128
fail_on_revert = true

[profile.network]
sepolia = { url = "${SEPOLIA_RPC_URL}", chain_id = 11155111 }
