[profile.default]
solc_version = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[invariant]
runs = 128
depth = 128
fail_on_revert = true

[profile.network]
sepolia = { url = "${SEPOLIA_RPC_URL}", chain_id = 11155111 }
